In [42]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torchvision import datasets,transforms
import torch.utils.data.dataloader as DataLoader
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [43]:
a = torch.zeros(2,3,4) # 全0张量，两个大的，大的里面有三个中的，里面各有四个数
print(a)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [44]:
print(a.size()) # a的大小
print(a.size(0)) # a的大小的第一个维度
print(a.size(2)) # a的大小的第三个维度

torch.Size([2, 3, 4])
2
4


In [45]:
b = a.reshape(4,3,2) # 将a的第一个维度变成4，第二个维度变成3，第三个维度变成2
print(b.size())
print(a.size()) # a不变，reshape不修改原数据

torch.Size([4, 3, 2])
torch.Size([2, 3, 4])


In [46]:
b = b.reshape(12,2) # 只要元素总个数不变，就可以进行reshape
print(b.size())

torch.Size([12, 2])


In [47]:
c = torch.ones(2,3,4) # 生成全1的数据
print(c)
c = torch.empty(2,3,4) # 生成空数据,但是不能用于训练,只能用于计算，随机数据
print(c)
c = torch.rand(2,3,4) # 生成随机数据,可以用于训练
print(c)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  2.8537e-01,  7.0295e+28,  6.1949e-04],
         [ 1.9154e-19,  5.1415e-11,  4.5976e+24,  1.2736e-14]],

        [[ 1.0023e-08,  1.3817e-19, -6.4437e+24, -2.1583e-35],
         [-3.0646e-19, -2.7671e+22, -9.3166e-26, -1.1395e-30],
         [-9.4431e+28, -1.6702e-09, -2.6175e-10, -6.2613e+24]]])
tensor([[[0.5594, 0.0108, 0.1033, 0.6323],
         [0.6431, 0.9099, 0.5354, 0.6635],
         [0.0638, 0.3147, 0.1561, 0.6271]],

        [[0.2996, 0.4180, 0.2278, 0.4558],
         [0.5846, 0.8172, 0.6419, 0.7195],
         [0.3131, 0.9798, 0.5608, 0.5478]]])


In [48]:
d = c.view(2,12) # 将c的第一个维度变成2，第二个维度变成12
print(d.size())
print(c.size()) # view不修改原数据
c[0][0][0] = 2 # 只能修改一个元素
c[0,0,0] = 1 # 与上面的效果一样
print(c[0,0,0])
print(d[0,0]) # view共用一个内存空间，所以修改c的元素也会修改d的元素

torch.Size([2, 12])
torch.Size([2, 3, 4])
tensor(1.)
tensor(1.)


In [50]:
a = torch.rand(2,3)
print(f"a的内容:\n{a}\n")
b = torch.max(a, 1) # dim = 0 表示按列求最大值，dim = 1 表示按行求最大值
print(f"b的内容:\n{b}\n") # b中包含两个内容：最大值，最大值的索引
print(f"b.indices的内容:\n{b.indices}\n")
print(f"b.indices.tolist()将其转换为list:\n{b.indices.tolist()}")

a的内容:
tensor([[0.9237, 0.5947, 0.7033],
        [0.2948, 0.4978, 0.8189]])

b的内容:
torch.return_types.max(
values=tensor([0.9237, 0.8189]),
indices=tensor([0, 2]))

b.indices的内容:
tensor([0, 2])

b.indices.tolist()将其转换为list:
[0, 2]
